const menuData = [
    {
    id: 1,
    title: "Product",
    newTab: false,
    singleManu: false,
    submenu: [
      {
        id: 41,
        title: "Platform Overview",
        description: "All you need to create stunning and high-converting landing pages",
        path: "/product/vision-software",
        iconbg: "#fdba74",
        icon:"fak fa-vision",
        newTab: false,
      },
      {
        id: 42,
        title: "API Integrations",
        description: "Connect your applications all into one workspace.",
        path: "/product/api-integrations",
          iconbg: "#0ea5e9",
        icon:"fa-duotone fa-webhook",
        newTab: false,
      },
      {
        id: 43,
        title: "Audit Compliance Software",
        description: "Inspection Information, Accreditations To Performance Reviews In One Place",
        path: "/product/audit-compliance-software",
        iconbg: "#a78bfa",
         icon:"fa-duotone fa-file-contract",
        newTab: false,
      },
      {
        id: 44,
        title: "On-Site Surveying App",
        description: "All you need to create stunning and high-converting landing pages",
        path: "/product/onsite-surveying-app",
        newTab: false,
        iconbg: "#1e3a8a",
        icon:"fa-duotone fa-mobile-signal",
        
      },
      {
        id: 45,
        title: "Asset Management (SAM)",
        description: "Record, Track, Trace And Monitor All Your assets in one place.",
        path: "/product/asset-management",
        iconbg: "#14b8a6",
        icon:"fa-duotone fa-shield-check",
        newTab: false,
      },
      {
        id: 48,
        title: "Asset Tagging App",
        description: "Tag and Track Your Assets Anywhere",
        path: "/product/asset-tagging",
        iconbg: "#ec6817",
         icon:"fak fa-vision-tag",
        newTab: false,
      },
            {
        id: 47,
        title: "Asbestos Compliance",
        description: "Featuring CAD Driven room location..",
        path: "/product/asbestos-risk-software",
        iconbg: "#fb7185",
        icon:"fak fa-asbestos",
        newTab: false,
      },
    ],
  },
      {
    id: 2,
    title: "Solutions",
    newTab: false,
    singleManu: false,
    submenu: [
      {
        id: 21,
        title: "Incident Management",
        description: "All you need to create stunning and high-converting landing pages",
        path: "/vision-software",
        iconbg: "#ea580c",
        icon:"fa-duotone fa-triangle-exclamation",
        newTab: false,
      },
      {
        id: 22,
        title: "ISO 45001:2018 Occupational Health & Safety Management",
        description: "All you need to create stunning and high-converting landing pages",
        path: "/contact",
           iconbg: "#1e3a8a",
        icon:"fa-duotone fa-webhookfa-duotone fa-file-certificate",
        newTab: false,
      },
      {
        id: 23,
        title: "Risk Management",
        description: "Inspection Information, Accreditations To Performance Reviews In One Place",
        path: "/contact",
        iconbg: "#5b21b6",
         icon:"fa-duotone fa-file-contract",
        newTab: false,
      },
      {
        id: 24,
        title: "ISO 9001:2015 Quality Management",
        description: "All you need to create stunning and high-converting landing pages",
        path: "/blog-sidebar",
        newTab: false,
        iconbg: "#1e3a8a",
        icon:"fa-duotone fa-file-certificate",
        
      },
      {
        id: 25,
        title: "Property/Estate Management",
        description: "Record, Track, Trace And Monitor All Your assets in one place.",
        path: "/blog-details",
        iconbg: "#14b8a6",
        icon:"fa-duotone fa-shield-check",
        newTab: false,
      },
      {
        id: 26,
        title: "ISO 45001:2018 Occupational Health & Safety Management",
        description: "Tag and Track Your Assets Anywhere",
        path: "/error",
        iconbg: "#1e3a8a",
         icon:"fa-duotone fa-file-certificate",
        newTab: false,
      },
            {
        id: 27,
        title: "Asbestos Management",
        description: "Featuring CAD Driven room location..",
        path: "/signup",
        iconbg: "#dc2626",
        icon:"fak fa-asbestos",
        newTab: false,
      },
           {
        id: 28,
        title: "PAS 79 Fire Risk Assessment",
        description: "Tag and Track Your Assets Anywhere",
        path: "/error",
        iconbg: "#1e3a8a",
         icon:"fa-duotone fa-file-certificate",
        newTab: false,
      },
    ],
  },

  {
    id: 4,
    title: "Customers",
    path: "/customers",
    newTab: false,
    singleManu: false,
  },
  {
    id: 5,
    title: "Support",
    path: "/support",
    singleManu: false,
    newTab: false,
  },
      {
    id: 6,
    title: "Company",
    newTab: true,
    singleManu: true,
    submenulist: [
           {
        id: 65,
        title: "Contact",
        path: "/contact",
        iconbg: "#ea580c",
        icon:"fa-duotone fa-triangle-exclamation",
        newTab: false,
      },
      {
        id: 61,
        title: "About",

        path: "/about",
        iconbg: "#ea580c",
        icon:"fa-duotone fa-triangle-exclamation",
        newTab: false,
      },
      {
        id: 62,
        title: "Blog",
        path: "/blog",
           iconbg: "#1e3a8a",
        icon:"fa-duotone fa-webhookfa-duotone fa-file-certificate",
        newTab: false,
      },
      {
        id: 63,
        title: "Partners",
        path: "/Partners",
        iconbg: "#5b21b6",
         icon:"fa-duotone fa-file-contract",
        newTab: false,
      },
      {
        id: 64,
        title: "Security",
        path: "/blog-sid",
        newTab: false,
        iconbg: "#1e3a8a",
        icon:"fa-duotone fa-file-certificate",
        
      },
   
    ],
  },

    {
    id: 7,
    title: "Pricing",
    path: "/contact",
    newTab: false,
     singleManu: false,
  },

];
export default menuData;
